const contemporary = {
    femaleNames: ["Olivia", "Emma", "Charlotte", "Amelia", "Sophia", "Isabella", "Ava", "Mia", "Evelyn", "Luna", "Harper", "Camila", "Sofia", "Scarlett", "Elizabeth", "Emily", "Chloe", "Violet", "Penelope", "Aria", "Abigail", "Avery", "Hazel", "Nora", "Madison", "Zoe", "Victoria", "Zoey", "Naomi", "Hannah", "Lucy", "Elena", "Leah", "Addison", "Natalie", "Delilah", "Madelyn", "Alice", "Ruby", "Claire", "Audrey", "Sadie", "Savannah", "Quinn", "Hailey", "Aubrey", "Emery", "Anna", "Skylar", "Jade", "Ariana", "Gabriella", "Adeline", "Lydia", "Sarah", "Raelynn", "Allison", "Vivian", "Maeve", "Samantha", "Melody", "Eva", "Clara", "Julia", "Juliette", "Piper", "Parker", "Eden", "Charlie", "Peyton", "Daisy", "Millie", "Margaret", "Melanie", "Mary", "Esther", "Mackenzie", "Valerie", "Reagan", "Summer", "Ashley", "Olive", "Andrea", "Sara", "Rosalie", "Bailey", "Callie", "Alexandra", "Faith"],
    maleNames: ["Liam", "Noah", "Oliver", "James", "John", "Mark", "Elijah", "William", "Lucas", "Benjamin", "Henry", "Theo", "Mateo", "Sebastian", "Levi", "Daniel", "Jack", "Asher", "Owen", "Samuel", "Michael", "Ethan", "Leo", "Jackson", "Mason", "Ezra", "Hudson", "Luca", "Aiden", "Joseph", "David", "Jacob", "Logan", "Luke", "Julian", "Gabriel", "Grayson", "Wyatt", "Matthew", "Dylan", "Isaac", "Anthony", "Thomas", "Jayden", "Santiago", "Cooper", "Caleb", "Charles", "Miles", "Christopher", "Nathan", "Joshua", "Andrew", "Adrian", "Cameron", "Nolan", "Waylon", "Eli", "Aaron", "Adam", "Axel", "Ryan", "Christian", "Ian", "Wesley", "Robert", "Jonathan", "Beau", "Micah", "Colton", "Jordan", "Jeremiah", "Parker", "Nicholas", "Xavier", "Dominic", "Hunter", "Austin", "Declan", "Emmett", "Milo", "Vincent", "Jasper", "Evan", "Chase", "Calvin", "Ashton", "Graham", "Leon", "Hayden", "Zachary", "Tyler", "Dean", "Maxwell", "Justin"],
    surnames: ["Smith", "Jones", "Taylor", "Brown", "Williams", "Wilson", "Johnson", "Davies", "Robinson", "Wright", "Thompson", "Evans", "Walker", "White", "Roberts", "Green", "Hall", "Wood", "Jackson", "Clark", "Murphy", "O'Brien", "Doyle", "Murray", "Tremblay", "Lee", "MacDonald", "Wilson", "Fisher", "Barnes", "Butler", "Perry", "Jenkins", "Ortiz", "Sullivan", "Morales", "Sanders", "Foster", "Myers", "Long", "Price", "Hughes", "Cruz", "Gray", "Richardson", "Diaz", "Cox", "Peterson", "Morris", "Parker", "Collins", "Campbell", "Stark", "Callahan", "Everdeen", "Montana", "O'Hara", "Starling", "Hassan", "Merrick", "Carnell", "Harper", "Paisley", "McKenna", "Cooper", "Fletcher", "Beaumont", "Beckett", "Laurier", "Hyde", "Hardy", "Rush", "Pierce", "Zade", "Harlow"]
};

const fantasy = {
    femaleNames: ["Raya", "Aria", "Scarlett", "Luna", "Zoey", "Aurora", "Paisley", "Everly", "Nova", "Isla", "Quinn", "Delilah", "Jade", "Athena", "Melody", "Iris", "Anastasia", "Eloise", "Trinity", "Genevieve", "Amara", "Rosalie", "Lila", "Zara", "Freya", "Zoe", "Thea", "Leia", "Phoebe", "Keira", "Ophelia", "Winter", "Bianca", "Dahlia", "Octavia", "Blair", "Wren", "Kara", "Lorelai", "Poppy", "Aurelia", "Astrid", "Zelda", "Lyra", "Mara", "Faye", "Annika", "Lara", "Calliope", "Kiera", "Paloma", "Zora", "Ingrid", "Tara", "Chiara", "Elodie", "Tegan", "Seraphina", "Xena", "Imogen", "Shea", "Ripley", "Avalon", "Persephone", "Juno", "Arwen", "Hermione", "Odette", "Beatrix", "Elowen", "Olympia", "Marta", "Emberly", "Zinnia", "Guinevere", "Una", "Lotus", "Cosima", "Xenia", "Allegra", "Mirabelle", "Ursula", "Gwendolen", "Valkyrie", "Cassia", "Isis", "Maris", "Astra", "Inga", "Rowena", "Vesper", "Morgana", "Apollonia", "Delphine", "Seraphine", "Thora", "Saffire", "Sorcha", "Kestrel", "Wisteria"],
    maleNames: ["Kai", "Roman", "Eli", "Xavier", "Zion", "Ezra", "Xander", "Milo", "River", "Zane", "Harrison", "Holden", "Griffin", "Abel", "Jude", "Axel", "Felix", "Leon", "Archer", "Martin", "Atlas", "Ronan", "Orion", "Elliot", "Gideon", "Titus", "Atticus", "Hector", "Odin", "Adonis", "Seth", "Logan", "Finn", "Cade", "Cyrus", "Angel", "Cole", "Drake", "Apollo", "Callum", "Forrest", "Casey", "Cullen", "Lucian", "Morgan", "Talon", "Caspian", "Fox", "Jack", "Leo", "Anakin", "Aldo", "Rhett", "Aries", "Evander", "Thor", "Bastian", "Kael", "Arrow", "Digby", "Noble", "Zephyr", "Beck", "Calix", "Lucien", "Cormac", "Cornelius", "Emrys", "Gareth", "Phineas", "West", "Dashiell", "Ender", "Ajax", "Perseus", "Tiberius", "Calder", "Bram", "Collins", "Stellan", "Cosmo", "Flint", "Remus", "Artemis", "Merlin", "Crane", "Oberon", "Galen", "Jareth", "Gregor", "York", "Sandor", "Acheron", "Peregrin", "Alf", "Abbot", "Digory", "Cal", "Hawke", "Byron"],
    surnames: ["Atwater", "Agassi", "Apatow", "Akagawa", "Averescu", "Arrington", "Agrippa", "Aiken", "Albertson", "Alexander", "Amado", "Anders", "Ashsorrow", "Humblecut", "Ashbluff", "Marblemax", "Armas", "Akka", "Aoki", "Aldrich", "Apak", "Alinsky", "Desai", "Darby", "Draper", "Dwyer", "Dixon", "Danton", "Desmith", "Ditka", "Dominguez", "Decker", "Dobermann", "Dunlop", "Dumont", "Dandridge", "Diamond", "Dobra", "Dukas", "Agnello", "Alterio", "Bidbury", "Botkin", "Benoit", "Biddercombe", "Baldwin", "Bennett", "Bourland", "Boadle", "Bender", "Best", "Bobshaw", "Bersa", "Belt", "Bourn", "Barke", "Beebe", "Banu", "Bozzelli", "Bogaerts", "Blanks", "evert", "Eastwood", "Elway", "Eslinger", "Ellerbrock", "Eno", "Endo", "Etter", "Ebersol", "Everson", "Esapa", "Ekker", "Eggleston", "Ermine", "Erickson", "Keller", "Kessler", "Kobayashi", "Klecko", "Kicklighter", "Kidder", "Kershaw", "Kaminsky", "Kirby", "Keene", "Kenny", "Keogh", "Kipps", "Kendrick", "Kuang", "Fairchild", "October", "Vespertine", "Fellowes", "Omen", "Willow", "Gannong", "Presto", "Windward", "Grell", "Powers", "Wixx", "Halliwell", "Quellings", "Xanthos", "Hightower", "Quill", "Xenides", "Idlewind", "Rast", "Yarrow", "Winddane", "Coldsprinter", "Hallowswift", "Yarborough", "Youngblood", "Yearwood", "Winters", "Shadegrove", "Rapidclaw", "Hazerider", "Yates", "Truthbelly", "McGillicutty", "McCabe"]
};

const scifi = {
    femaleNames: ["Skylar", "Genesis", "Sevyn", "Serenity", "Eden", "Ariel", "Lucia", "Ember", "Kali", "Cali", "Haven", "Evie", "Phoenix", "Kenzie", "Zuri", "Harlow", "Jada", "Skye", "Tatum", "Carmen", "Sierra", "Lorelei", "Maia", "Justice", "Karsyn", "Shiloh", "Amalia", "Dream", "Mercy", "Rhea", "Amaia", "Lexie", "Tori", "Kai", "Veda", "Yasmin", "Zia", "Rae", "Halo", "Artemis", "Indigo", "Klara", "Sapphire", "Amethyst", "Gaia", "Raine", "Rain", "Navy", "Calista", "Taya", "Soleil", "Karis", "Calla", "Venus", "Sol", "Ryder", "Azure", "Caia", "Delta", "Omega", "Lux", "Kalliope", "Sirena", "Vega", "Gemini", "Leo", "Onyx", "Tavia", "Jupiter", "Odessa", "Andromeda", "Callista", "Carys", "Seren", "Alaska", "Elektra", "Skai", "Sona", "Azura", "Dasha", "Arcadia", "Mali", "Saskia", "Starla", "Electra", "Cressida", "Tove", "Oceana", "Lumina", "Fantasia", "Cerise", "Exie", "Astoria", "Blaise", "Enyo", "Alura", "Europa", "Polaris", "Sayer", "Signe"],
    maleNames: ["Cisco", "Maverick", "Jace", "Ryker", "Maximus", "Jax", "Knox", "Colt", "Phoenix", "Ace", "Zander", "Chance", "Cash", "Killian", "Jett", "Dante", "Gage", "Jay", "Zayne", "Zaiden", "Kian", "Dax", "Ronin", "Rhys", "Dexter", "Nikolai", "Zachariah", "Cairo", "Wilder", "Tatum", "Soren", "Callen", "Crew", "Uriah", "Axton", "Cassius", "Mekhi", "Kohen", "Zeke", "Alvin", "Tripp", "Titan", "Bronson", "Grey", "Trace", "Emory", "Ares", "Gray", "Keanu", "Kaiser", "Cillian", "Van", "Mac", "Darian", "Blaze", "Nova", "Onyx", "Cian", "Ephraim", "Idris", "Creed", "Alaric", "Torin", "Benedict", "Bowie", "Kalel", "Link", "Mika", "Shia", "Jet", "Zeus", "Vaughn", "Klay", "Blaise", "Caius", "Alston", "Azriel", "Cassian", "Sasha", "Sven", "Draco", "Pax", "Cael", "Athan", "Oren", "Colm", "Malachy", "Nero", "Thane", "Blade", "Calloway", "Aurelius", "Axe", "Ion", "Keir", "Finnian", "Chess", "Jayceon", "Astro", "Delta"],
    surnames: ["Ryker", "Sisko", "Steele", "Stryker", "Axelrod", "Sevyn", "Zion", "Loxley", "Rivera", "Cipriani", "Sorrentino", "Dutch", "Dupree", "Easton", "Mercier", "Bosco", "Bowman", "Wolfe", "Axton", "Powers", "Armstrong", "Bull", "Marshall", "Russo", "Burbeck", "Dune", "Tremaine", "Reynolds", "Cartwright", "Dunn", "Hawkins", "Hart", "McCarthy", "Underwood", "Shields", "Bourne", "MacArthur", "Maxx", "Rhinehart", "Acer", "Bachman", "Blackwood", "Dredd", "Dixon", "Fox", "Halifax", "Heathcliff", "Lourdes", "Stetson", "Thoreau", "Twain", "Vesper", "Volt", "Washburne", "Xiomara", "Bishop", "Bridger", "Dax", "Cobain", "Dumont", "Jagger", "Jaxon", "Styles", "Fielding", "Aphelion", "Furi", "Gibbethon", "Gregorios", "Nadir", "Silvius", "Umbra"]
};

const historical = {
    femaleNames: ["Eleanor", "Hazel", "Lily", "Maya", "Josephine", "Eloise", "Cecilia", "Freya", "Ruth", "Zara", "Diana", "Vera", "Angela", "Mabel", "Frances", "Dorothy", "Virginia", "Clementine", "Anne", "Margo", "Louisa", "Florence", "Nellie", "Zora", "Beatrix", "Ida", "Agnes", "Rosalind", "Imogen", "Joan", "Agatha", "Millicent", "Henrietta", "Brigitte", "Indira", "Alice", "Maude", "Matilda", "Eliza", "Ada", "Harriet", "Betty", "Maria", "Gloria", "Penelope", "Chloe", "Margaret", "Deborah", "Charlotte", "Margot", "Lucy", "Scarlett", "Adeline", "Amelia", "Simone", "Ingrid", "Olivia", "Barbara", "Rose", "Sophie", "Clara", "Beatrice", "Sojourner", "Evelyn", "Rosa", "Elizabeth", "Emmeline", "Emma", "Doris", "Grace", "Edith", "Audrey", "Helen", "Sophia", "Ella", "Emily", "Jacqueline", "Caroline", "Mary", "Nancy", "Isabella", "Bella", "Anastasia", "Hypatia", "Coco", "Greta", "Gertrude", "Cleopatra", "Marilyn", "Frida", "Victoria", "Susan", "Abigail", "Anna", "Catherine", "Constance", "Artemisia", "Wilma", "Katherine"],
    maleNames: ["George", "Henry", "Thomas", "John", "Alexander", "Martin", "Neil", "Benjamin", "Oliver", "Paul", "James", "Samuel", "Albert", "William", "Richard", "Theodore", "Franklin", "Mark", "Cicero", "Cesar", "Ralph", "Frederick", "Oscar", "Sidney", "Muhammad", "Abraham", "Julius", "Marcus", "Charles", "Maximus", "Cassius", "Augustus", "David", "Orville", "Aurelius", "Eli", "Felix", "Daniel", "Audie", "Nikola", "Joseph", "Quintus", "Lucius", "Winston", "Rufus", "Isaac", "Atticus", "Ronald", "Lincoln", "Woodrow", "Andrew", "Romulus", "Brutus", "Kareem", "Marlon", "Anthony", "Nero", "Gabriel", "Cornelius", "Titus", "Carter", "Thor", "Magnus", "Humphrey", "Dwight", "Everett", "Nelson", "Ty", "Isaiah", "Arthur", "Josiah", "Clark", "Wilbur", "Cato", "Booker", "Charlton", "Jonas", "Caesar", "Leonardo", "Duke", "Horace", "Octavius", "Bernard", "Warren", "Decimus", "Andreas", "Florian", "Carlos", "Ulysses", "Langston", "Bartholomew", "Proximo", "Edward", "Aristotle", "Commodus", "Ezekiel", "Amadeus", "Conrad", "Achilles", "Hugo"],
    surnames: ["Acker", "Anderton", "Barney", "Beckwith", "Berrycloth", "Birdwhistle", "Browning", "Camden", "Churchill", "Clayden", "Compton", "Culpepper", "Dankworth", "Darlington", "Davenport", "Deighton", "Dryden", "Eastaughffe", "Eaton", "Elton", "Enfield", "Everly", "Gastrell", "Garfield", "Graham", "Hastings", "Loughty", "Macca", "McQuoid", "Pussett", "Slora", "Spinster", "Tumbler", "Abram", "Ajax", "Bread", "Bythesea", "Cotton", "Edevane", "Farley", "Fernsby", "Miracle", "Relish", "Villin", "Ainsley", "Allerton", "Altham", "Anstey", "Appleton", "Ashley", "Astley", "Atterton", "Axton", "Badger", "Barton", "Barlow", "Bentley", "Berkeley", "Blythe", "Bradshaw", "Chatham", "Chester", "Cornish", "Crawford", "Dalton", "Darby", "Denver", "Emsworth", "Harlan", "Middleton", "Oakley", "Northcott", "Keene", "Everleigh", "Denholm"]
};

